export type OpsItem = {
  label: string;
  href: string;
  description?: string;
};

export type OpsGroup = {
  title: string;
  items: OpsItem[];
};

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/\//g, "-")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

const buildGroup = (title: string, base: string, labels: string[]): OpsGroup => ({
  title,
  items: labels.map((label) => ({
    label,
    href: `/ops/${base}/${slugify(label)}`,
  })),
});

export const coreNavigation: OpsGroup[] = [
  {
    title: "Core",
    items: [
      { label: "Dashboard", href: "/dashboard" },
      { label: "Users", href: "/users" },
      { label: "Projects", href: "/projects" },
      { label: "Tasks", href: "/tasks" },
      { label: "Billing", href: "/billing" },
      { label: "Reports", href: "/reports" },
      { label: "Settings", href: "/settings" },
    ],
  },
];

export const opsNavigation: OpsGroup[] = [
  buildGroup("Dashboard", "dashboard", [
    "Overview",
    "KPI Summary",
    "Activity Feed",
    "Trends & Insights",
    "Real-time Monitor",
    "Quick Actions",
  ]),
  buildGroup("User Management", "user-management", [
    "Users",
    "User List",
    "User Details",
    "Create User",
    "Edit User",
    "Bulk Actions",
    "Roles & Permissions",
    "Roles",
    "Permission Matrix",
    "Policy Rules",
    "Access Logs",
    "Teams & Groups",
    "Teams",
    "Departments",
    "User Groups",
    "Invitations",
    "Pending Invites",
    "Invite Settings",
    "Profiles & Identity",
    "Profile Fields",
    "Verification Status",
  ]),
  buildGroup("Authentication & Security", "authentication-security", [
    "Authentication",
    "Sign-in Methods",
    "Password Policy",
    "MFA / 2FA",
    "SSO (SAML/OAuth)",
    "Sessions",
    "Active Sessions",
    "Device History",
    "Force Logout",
    "Security Center",
    "Security Alerts",
    "Risk Scores",
    "IP Allowlist / Blocklist",
    "Geo Restrictions",
    "Audit & Compliance",
    "Audit Logs",
    "Data Access Logs",
    "Change History",
    "Keys & Secrets",
    "API Keys",
    "Webhooks Secrets",
    "Token Management",
  ]),
  buildGroup("Organization & Workspace", "organization-workspace", [
    "Organization Settings",
    "Company Profile",
    "Branding",
    "Localization",
    "Workspaces",
    "Workspace List",
    "Workspace Settings",
    "Workspace Members",
    "Resource Ownership",
    "Transfers",
    "Shared Resources",
  ]),
  buildGroup("Content Management", "content-management", [
    "Content",
    "Pages",
    "Posts / Articles",
    "Categories",
    "Tags",
    "Media Library",
    "Uploads",
    "Folders",
    "Image Optimization",
    "Editor Tools",
    "Drafts",
    "Revisions",
    "Publishing Schedule",
    "Comments & Moderation",
    "Pending",
    "Reported",
    "Banned Words",
  ]),
  buildGroup("Product / Catalog", "product-catalog", [
    "Products",
    "Product List",
    "Variants",
    "Attributes",
    "Collections",
    "Inventory",
    "Stock Levels",
    "Warehouses",
    "Stock Movements",
    "Pricing",
    "Price Lists",
    "Discounts",
    "Coupons",
    "Promotions",
    "Reviews",
    "Review Queue",
    "Ratings Analytics",
  ]),
  buildGroup("Orders & Fulfillment", "orders-fulfillment", [
    "Orders",
    "Order List",
    "Order Details",
    "Status Pipeline",
    "Payments",
    "Transactions",
    "Refunds",
    "Chargebacks",
    "Shipping",
    "Carriers",
    "Shipping Labels",
    "Delivery Zones",
    "Returns",
    "Return Requests",
    "Return Reasons",
    "Invoices",
    "Invoice Templates",
    "Tax Documents",
  ]),
  buildGroup("Customer Support", "customer-support", [
    "Customers",
    "Customer List",
    "Customer Profile",
    "Customer Segments",
    "Tickets",
    "Inbox",
    "SLA Queue",
    "Assignments",
    "Live Chat",
    "Conversations",
    "Chat Widgets",
    "Knowledge Base",
    "Articles",
    "Categories",
    "Feedback",
    "NPS / CSAT",
    "Feature Requests",
  ]),
  buildGroup("Marketing", "marketing", [
    "Campaigns",
    "Email Campaigns",
    "SMS Campaigns",
    "Push Notifications",
    "Segmentation",
    "Audiences",
    "Rules Builder",
    "Automation",
    "Flows",
    "Triggers & Actions",
    "SEO",
    "Metadata Manager",
    "Sitemap",
    "Redirects",
    "Referrals & Affiliates",
    "Affiliate Programs",
    "Payouts",
  ]),
  buildGroup("Analytics & Reporting", "analytics-reporting", [
    "Analytics",
    "Traffic Analytics",
    "Conversion Funnel",
    "Retention / Cohorts",
    "Reports",
    "Scheduled Reports",
    "Custom Reports",
    "Export Center",
    "Data Visualization",
    "Charts Library",
    "Dashboard Builder",
  ]),
  buildGroup("Finance & Billing", "finance-billing", [
    "Billing",
    "Plans",
    "Subscriptions",
    "Usage Metering",
    "Invoices",
    "Invoice History",
    "Tax Settings",
    "Payments",
    "Payment Methods",
    "Payouts",
    "Credits",
    "Coupons",
    "Wallet / Credits",
  ]),
  buildGroup("Notifications & Communication", "notifications-communication", [
    "Notifications",
    "Templates",
    "Delivery Channels",
    "Notification Rules",
    "Message Center",
    "Broadcast Messages",
    "Announcements",
    "Email Templates",
    "Template Builder",
    "Variables",
  ]),
  buildGroup("Integrations", "integrations", [
    "Integrations Hub",
    "Connected Apps",
    "Marketplace",
    "Webhooks",
    "Endpoints",
    "Retry Queue",
    "Event Types",
    "API",
    "API Docs",
    "API Keys",
    "Rate Limits",
    "Third-party Services",
    "Payments (Stripe etc.)",
    "Analytics (GA etc.)",
    "Storage (S3 etc.)",
  ]),
  buildGroup("Workflow & Automation", "workflow-automation", [
    "Workflow Builder",
    "Rule Engine",
    "Approvals",
    "Assignments",
    "Jobs & Queues",
    "Background Jobs",
    "Retries",
    "Scheduling",
    "Cron Jobs",
    "Task Scheduler",
  ]),
  buildGroup("Settings", "settings", [
    "General Settings",
    "App Settings",
    "Themes",
    "Language & Region",
    "Feature Flags",
    "Environments",
    "Rollout Rules",
    "Data Management",
    "Import",
    "Export",
    "Backup & Restore",
  ]),
  buildGroup("Logs & Monitoring", "logs-monitoring", [
    "System Health",
    "Status",
    "Uptime",
    "Monitoring",
    "Error Tracking",
    "Performance Metrics",
    "Latency",
    "Logs",
    "Application Logs",
    "Security Logs",
    "Request Logs",
  ]),
  buildGroup("Admin Tools", "admin-tools", [
    "Admin Console",
    "Global Search",
    "Admin Actions",
    "Maintenance",
    "Maintenance Mode",
    "Cache Management",
    "Bulk Operations",
    "Batch Updates",
    "Batch Delete",
    "Data Inspector",
    "Raw Data Viewer",
    "Relations Viewer",
  ]),
  buildGroup("Legal & Compliance", "legal-compliance", [
    "Privacy",
    "Data Requests (DSAR)",
    "Consent Management",
    "Compliance",
    "GDPR Tools",
    "Retention Policies",
    "Terms & Policies",
    "Terms Pages",
    "Policy Updates",
  ]),
  buildGroup("Developer Tools", "developer-tools", [
    "Environments",
    "Dev / Staging / Prod",
    "Releases",
    "Changelog",
    "Deployment History",
    "Sandbox",
    "Test Data Generator",
    "Feature Toggles",
    "Experiments (A/B)",
  ]),
  buildGroup("Help & Documentation", "help-documentation", [
    "Help Center",
    "System Documentation",
    "Release Notes",
    "Contact Support",
    "Shortcuts / Hotkeys",
  ]),
];

export const opsItemsIndex = opsNavigation.flatMap((group) => group.items);
